document.writeln("<!-- /*");
document.writeln("* Bootstrap 5");
document.writeln("* Template Name: Furni");
document.writeln("* Template Author: Untree.co");
document.writeln("* Template URI: https://untree.co/");
document.writeln("* License: https://creativecommons.org/licenses/by/3.0/");
document.writeln("*/ -->");
document.writeln("<!doctype html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, shrink-to-fit=no\'>");
document.writeln("    <meta name=\'author\' content=\'Untree.co\'>");
document.writeln("    <link rel=\'shortcut icon\' href=\'favicon.png\'>");
document.writeln("");
document.writeln("    <meta name=\'description\' content=\'\' />");
document.writeln("    <meta name=\'keywords\' content=\'bootstrap, bootstrap4\' />");
document.writeln("");
document.writeln("    <!-- Bootstrap CSS -->");
document.writeln("    <link href=\'css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'css/tiny-slider.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'css/style.css\' rel=\'stylesheet\'>");
document.writeln("    <title>MoiMoi.fi</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <!-- Start Footer Section -->");
document.writeln("    <footer class=\'footer-section\'>");
document.writeln("        <div class=\'container relative\'>");
document.writeln("");
document.writeln("            <!-- <div class=\'sofa-img\'>");
document.writeln("				<img src=\'images/sofa.png\' alt=\'Image\' class=\'img-fluid\'>");
document.writeln("			</div> -->");
document.writeln("");
document.writeln("            <!-- <div class=\'row\'>");
document.writeln("				<div class=\'col-lg-8\'>");
document.writeln("					<div class=\'subscription-form\'>");
document.writeln("						<h3 class=\'d-flex align-items-center\'><span class=\'me-1\'><img src=\'images/envelope-outline.svg\'");
document.writeln("									alt=\'Image\' class=\'img-fluid\'></span><span>Subscribe to Newsletter</span></h3>");
document.writeln("");
document.writeln("						<form action=\'#\' class=\'row g-3\'>");
document.writeln("							<div class=\'col-auto\'>");
document.writeln("								<input type=\'text\' class=\'form-control\' placeholder=\'Enter your name\'>");
document.writeln("							</div>");
document.writeln("							<div class=\'col-auto\'>");
document.writeln("								<input type=\'email\' class=\'form-control\' placeholder=\'Enter your email\'>");
document.writeln("							</div>");
document.writeln("							<div class=\'col-auto\'>");
document.writeln("								<button class=\'btn btn-primary\'>");
document.writeln("									<span class=\'fa fa-paper-plane\'></span>");
document.writeln("								</button>");
document.writeln("							</div>");
document.writeln("						</form>");
document.writeln("");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div> -->");
document.writeln("");
document.writeln("            <div class=\'row g-5 mb-5\'>");
document.writeln("                <div class=\'col-lg-4\'>");
document.writeln("                    <div class=\'mb-4 footer-logo-wrap\'><a href=\'#\' class=\'footer-logo\'>MoiMoi.fi</a></div>");
document.writeln("");
document.writeln("                    <!-- <ul class=\'list-unstyled custom-social\'>");
document.writeln("						<li><a href=\'#\'><span class=\'fa fa-brands fa-facebook-f\'></span></a></li>");
document.writeln("						<li><a href=\'#\'><span class=\'fa fa-brands fa-twitter\'></span></a></li>");
document.writeln("						<li><a href=\'#\'><span class=\'fa fa-brands fa-instagram\'></span></a></li>");
document.writeln("						<li><a href=\'#\'><span class=\'fa fa-brands fa-linkedin\'></span></a></li>");
document.writeln("					</ul> -->");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <div class=\'col-lg-8\'>");
document.writeln("                    <div class=\'row links-wrap\'>");
document.writeln("                        <div class=\'col-6 col-sm-6 col-md-3\'>");
document.writeln("                            <ul class=\'list-unstyled\'>");
document.writeln("                                <li><a href=\'#\'>Etusivu</a></li>");
document.writeln("                                <li><a href=\'#\'>Suojat</a></li>");
document.writeln("                                <li><a href=\'#\'>Kuulokkeet</a></li>");
document.writeln("                                <li><a href=\'#\'>Muut</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                        <!-- Hiden Section Start-->");
document.writeln("                        <div class=\'col-6 col-sm-6 col-md-3 hidenFooter\'>");
document.writeln("                            <ul class=\'list-unstyled\'>");
document.writeln("                                <li><a href=\'#\'>S</a></li>");
document.writeln("                                <li><a href=\'#\'>K</a></li>");
document.writeln("                                <li><a href=\'#\'>L</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("");
document.writeln("                        <div class=\'col-6 col-sm-6 col-md-3 hidenFooter\'>");
document.writeln("                            <ul class=\'list-unstyled\'>");
document.writeln("                                <li><a href=\'#\'>YHTEYSTIEDOT</a></li>");
document.writeln("                                <li><a href=\'#\'>Our team</a></li>");
document.writeln("                                <li><a href=\'#\'>Leadership</a></li>");
document.writeln("                                <li><a href=\'#\'>Privacy Policy</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </div><!-- Hiden Section End-->");
document.writeln("");
document.writeln("                        <div class=\'col-6 col-sm-6 col-md-3\'>");
document.writeln("                            <ul class=\'list-unstyled\'>");
document.writeln("                                <li class=\'ContactInfo\'><span>YHTEYSTIEDOT</span></li>");
document.writeln("                                <li><a href=\'#\'>Puhelin: +358 45 279 1811</a></li>");
document.writeln("                                <li><a href=\'#\'>Email: xiraliyasin104@outlook.com</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'border-top copyright\'>");
document.writeln("                <div class=\'row pt-4\'>");
document.writeln("                    <div class=\'col-lg-6\'>");
document.writeln("                        <p class=\'mb-2 text-center text-lg-start\'>Copyright &copy;");
document.writeln("                            2022 Digital Nordic International");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                    <div class=\'col-lg-6 text-center text-lg-end\'>");
document.writeln("                        <ul class=\'list-unstyled d-inline-flex ms-auto\'>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </footer>");
document.writeln("    <!-- End Footer Section -->");
document.writeln("");
document.writeln("");
document.writeln("    <script src=\'js/bootstrap.bundle.min.js\'></script>");
document.writeln("    <script src=\'js/tiny-slider.js\'></script>");
document.writeln("    <script src=\'js/custom.js\'></script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");