document.writeln("<!-- /*");
document.writeln("* Bootstrap 5");
document.writeln("* Template Name: Furni");
document.writeln("* Template Author: Untree.co");
document.writeln("* Template URI: https://untree.co/");
document.writeln("* License: https://creativecommons.org/licenses/by/3.0/");
document.writeln("*/ -->");
document.writeln("<!doctype html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, shrink-to-fit=no\'>");
document.writeln("    <meta name=\'author\' content=\'Untree.co\'>");
document.writeln("    <link rel=\'shortcut icon\' href=\'favicon.png\'>");
document.writeln("");
document.writeln("    <meta name=\'description\' content=\'\' />");
document.writeln("    <meta name=\'keywords\' content=\'bootstrap, bootstrap4\' />");
document.writeln("");
document.writeln("    <!-- Bootstrap CSS -->");
document.writeln("    <link href=\'css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'css/tiny-slider.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'css/style.css\' rel=\'stylesheet\'>");
document.writeln("    <title>Furni Free Bootstrap 5 Template for Furniture and Interior Design Websites by Untree.co </title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("    <!-- Start Header/Navigation -->");
document.writeln("    <nav class=\'custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark\' arial-label=\'Furni navigation bar\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <a class=\'navbar-brand\' href=\'index.html\'>MoiMoi.fi<span></span></a>");
document.writeln("            <button class=\'navbar-toggler\' type=\'button\' data-bs-toggle=\'collapse\' data-bs-target=\'#navbarsFurni\'");
document.writeln("                aria-controls=\'navbarsFurni\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("                <span class=\'navbar-toggler-icon\'></span>");
document.writeln("            </button>");
document.writeln("            <div class=\'collapse navbar-collapse\' id=\'navbarsFurni\'>");
document.writeln("                <ul class=\'custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0\'>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link\' href=\'index.html\'>Etusivu</a></li>");
document.writeln("                    <li><a class=\'nav-link\' href=\'suojat.html\'>Suojat</a></li>");
document.writeln("                    <li><a class=\'nav-link\' href=\'Kuulokkeet.html\'>Kuulokkeet</a></li>");
document.writeln("                    <li><a class=\'nav-link\' href=\'lataus.html\'>Lataus</a></li>");
document.writeln("                    <li><a class=\'nav-link\' href=\'muut.html\'>Muut</a></li>");
document.writeln("                    <!-- <li><a class=\'nav-link\' href=\'contact.html\'>Contact us</a></li> -->");
document.writeln("                </ul>");
document.writeln("                <ul class=\'custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5\'>");
document.writeln("                    <!-- <li><a class=\'nav-link\' href=\'#\'><img src=\'images/user.svg\'></a></li> -->");
document.writeln("                    <li><a class=\'nav-link\' href=\'contact.html\'><img src=\'images/emailIcon_red.png\' height=\'30\'");
document.writeln("                                width=\'30\'>");
document.writeln("                            xiraliyasin104@outlook.com</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </nav>");
document.writeln("    <script src=\'js/highLightCurrentNav.js\'></script>");
document.writeln("    <!-- End Header/Navigation -->");
document.writeln("");
document.writeln("    <script src=\'js/bootstrap.bundle.min.js\'></script>");
document.writeln("    <script src=\'js/tiny-slider.js\'></script>");
document.writeln("    <script src=\'js/custom.js\'></script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");